### ISSUE TITLE
Error while compile and run test demo

### ISSUE THREAD

**Issue by cryptomadco** [nautilus-fuzz/nautilus#2]
Hi !
I just followed your instruction to fuzz the test.c demo with nautilus but I got this :

```
Compiling textwrap v0.11.0
error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/crypt/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.3.3/src/lib.rs:89:34
   |
89 | #![cfg_attr(feature = "nightly", feature(const_fn))]
   |                                  ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try rustc --explain E0554.
error: could not compile lock_api.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Also, I didn't succeed at running this command :
`git clone 'git@github.com:nautilus-fuzz/nautilus.git'`

Because I got this error :
```
Cloning into 'nautilus'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Thus I just cloned the repository in this way :
`git clone https://github.com/nautilus-fuzz/nautilus.git`

Any workaround for the first error ?

**Comment by eqv** [comment]
As the compiler states: "may not be used on the stable release channel", you should use rust nightly. 
The second error is due to the fact that you don't have a ssh key for your github account.
