### ISSUE TITLE
regex_mutator always outputting empty strings

### ISSUE THREAD

**Issue by omergreen** [nautilus-fuzz/nautilus#24]
https://github.com/nautilus-fuzz/nautilus/blob/b6fa83df173500e0f092291d0ac0346502d50760/regex_mutator/src/lib.rs#L171

Should probably be `while !stack.is_empty()`

**Comment by eqv** [comment]
that is most certainly correct! Would love to merge a pull request.

**Comment by eqv** [comment]
Much appreciated!
