### ISSUE TITLE
some errors while fuzzing

### ISSUE THREAD

**Issue by bat-serjo** [nautilus-fuzz/nautilus#4]
I get such errors while fuzzing. Should I be worried?

thread 'fuzzer_18' panicked at 'internal error: entered unreachable code', grammartec/src/tree.rs:350:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'fuzzer_10' panicked at 'internal error: entered unreachable code', grammartec/src/tree.rs:350:17
thread 'fuzzer_20' panicked at 'internal error: entered unreachable code', grammartec/src/tree.rs:350:17

I also get things like "found fu**y bit 4299"

**Comment by eqv** [comment]
https://github.com/nautilus-fuzz/nautilus/blob/master/grammartec/src/tree.rs#L349 <- this looks pretty worrying to me. It seems there is something missing in the regex implementation. 

the fu**y bits part just means that bit 4299 in the bitmap was nondeterministic. If you fuzz complex targets that is to be expected. Could be caused by all kinds of things: random GC stuff, different keys for keyed hash functions in hashmaps leading to different collision patterns etc.

**Comment by eqv** [comment]
I think the quickfix would be to not use the regex part. I will look into this

**Comment by eqv** [comment]
Would you mind sharing your grammar? Or maybe a fraction that still triggers the issue?

**Comment by eqv** [comment]
Could it be that you start your grammar with a regex rule?

**Comment by eqv** [comment]
should be fixed by 50a806be8a0fa84f178c20d6839df196328f20ae. If you can confirm this, please close this issue.

**Comment by bat-serjo** [comment]
Here's the grammar I use
#ctx.rule(NONTERM: string, RHS: string|bytes) adds a rule NONTERM->RHS. We can use {NONTERM} in the RHS to request a recursion..
ctx.rule("START","{IAC}")
ctx.rule("IAC", u"{CMD}{BLA}{LETTER}{STRING}{IAC}")
ctx.rule("IAC", u"")
ctx.rule("CMD", "\xff")
ctx.rule("CMD", "{BLA}")
ctx.rule("BLA", "\xff")
ctx.rule("BLA", "\xfe")
ctx.rule("BLA", "\xfd")
ctx.rule("BLA", "\xfc")
ctx.rule("BLA", "\xfb")
ctx.rule("BLA", "\xfa")
ctx.rule("BLA", "\xf9")
ctx.rule("BLA", "\xf8")
ctx.rule("BLA", "\xf7")
ctx.rule("BLA", "\xf6")
ctx.rule("BLA", "\xf5")
ctx.rule("BLA", "\xf4")
ctx.rule("BLA", "\xf3")
ctx.rule("BLA", "\xf2")
ctx.rule("BLA", "\xf1")
ctx.rule("BLA", "\xf0")
ctx.rule("BLA", "\xff\xfa\x18\x00{STRING}")
#ctx.regex("LETTER", "[\x00-\x41]*")
ctx.regex("LETTER", "[\x00-\x36]*\x00*")
#ctx.rule("STRING", "")
ctx.regex("STRING", "[\x00-\x7f]*\x00*")
#ctx.regex("STRING", "[\x10-\x7f]+\x00*")

**Comment by bat-serjo** [comment]
looks fixed with that last commit.
