### ISSUE TITLE
Panicked while fuzzing

### ISSUE THREAD

**Issue by Changochen** [nautilus-fuzz/nautilus#6]
Hi, I am trying to set up nautilus. When I use the grammar of javascript to test sqlite, it panicked with the following log after running for 33 mins:
```
thread 'fuzzer_1' panicked at 'couldn't read child hello: Custom { kind: TimedOut, error: "timed out waiting for fd to be ready" }', forksrv/src/lib.rs:95:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'RAND_2698731594: Any', fuzzer/src/main.rs:495:9
```

The CMD line I am using is: `cargo run --release -- -g grammars/javascript_new.py -o /tmp/workdir -- ~/sqlite/bld2/sqlite3 -init @@`

**Comment by eqv** [comment]
That means that the forkserver wasn't started properly. Can you confirm that AFl is able to fuzz the same compiled target?

**Comment by Changochen** [comment]
I think the forkserver should be set up since it has run for 30 mins before it panicked. Both afl and afl++ are able to fuzz the same binary without error.

**Comment by eqv** [comment]
So the Fuzzer found a bunch of inputs in the first 30 minutes, but failed at that position during a running fuzzing campaign?  The only option that I see is that the target crashed in some way that wasn't detected (maybe issuing a shutodwn command?), and then  https://github.com/nautilus-fuzz/nautilus/blob/master/fuzzer/src/main.rs#L120 tried restarting the forkserver but wasn't able to (some lock file or something like that?). If this problem keeps reappearing you can try to place an unwrap at forksrv/src/lib.rs:95:17 and enable RUST_BACKTRACE=1 to see if that might be the case.

**Comment by Changochen** [comment]
`So the Fuzzer found a bunch of inputs in the first 30 minutes, but failed at that position during a running fuzzing campaign?`: Yes.

I see. I will try your suggestion. Thanks for the help!

**Comment by eqv** [comment]
Cool, if you manage to produce a reproducing test target/procedure with similar behavior (preferably in less than 30 minutes), I will gladly have a look at this issue!

**Comment by Changochen** [comment]
It seems the problem only apears once. I think this issue can be closed now. Thanks for the help again!

**Comment by eqv** [comment]
Hmm dang, if it ever reappears, please don't hesitate to reopen the issue!
